
#https://www.fastprep.io/problems/amazon-get-min-errors

def get_min_errors(error_string, x, y):
    n = len(error_string)
    dp = [0] * n  # dp[i] - the min errors generated by string error_string[0..i]

    ctn0 = 1 if error_string[0] == '0' else 0
    ctn1 = 0 if error_string[0] == '0' else 1

    for i in range(1, n):
        c = error_string[i]
        if c == '0':
            dp[i] = dp[i - 1] + ctn1 * y
            ctn0 += 1
        elif c == '1':
            dp[i] = dp[i - 1] + ctn0 * x
            ctn1 += 1
        else:  # c = '!'
            if ctn1 * y <= ctn0 * x:  # c = '0'
                dp[i] = dp[i - 1] + ctn1 * y
                ctn0 += 1
            else:
                dp[i] = dp[i - 1] + ctn0 * x
                ctn1 += 1

    return dp[-1]

# Example usage:
error_string = "101!1"
x_value = 2
y_value = 3
result = get_min_errors(error_string, x_value, y_value)
print(f"Minimum errors: {result}")


# Example usage:
error_string = "01!0"
x_value = 2
y_value = 2
result = get_min_errors(error_string, x_value, y_value)
print(f"Minimum errors: {result}")


# Example usage:
error_string = "!!!!!!!"
x_value = 23
y_value = 27
result = get_min_errors(error_string, x_value, y_value)
print(f"Minimum errors: {result}")
